### ISSUE TITLE
error when running gen_token.py

### ISSUE THREAD

**Issue by mohitjoshi155** [l3v11/SearchX#21]
Traceback (most recent call last):
  File "/home/.local/lib/python3.7/site-packages/google/auth/transport/requests.py", line 26, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 28, in <module>
    from six.moves import queue
  File "/usr/lib/python3/dist-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/lib/python3/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.7/queue.py", line 3, in <module>
    import threading
  File "/usr/lib/python3.7/threading.py", line 8, in <module>
    from traceback import format_exc as _format_exc
ImportError: cannot import name 'format_exc' from 'traceback' (/usr/lib/python3.7/traceback.py)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "gen_token.py", line 4, in <module>
    from google.auth.transport.requests import Request
  File "/home/.local/lib/python3.7/site-packages/google/auth/__init__.py", line 17, in <module>
    import logging
  File "/usr/lib/python3.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections.abc
  File "/usr/lib/python3.7/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/lib/python3.7/tokenize.py", line 35, in <module>
    from token import *
  File "/gen_token.py", line 4, in <module>
    from google.auth.transport.requests import Request
  File "/home/.local/lib/python3.7/site-packages/google/auth/transport/requests.py", line 35, in <module>
    caught_exc,
  File "<string>", line 3, in raise_from
ImportError: The requests library is not installed, please install the requests package to use the requests transport.

i already have requests installed with pip3 install requests

**Comment by l3v11** [comment]
@mohitjoshi155 I've run the script on my system. It's working perfectly. Issue is from your system, check again.
